services:
  web:
    image: blog
    container_name: blog-api
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=mongodb://db:27017/blog-api
    depends_on:
      - db

  db:
    image: blog
    container_name: blog-api-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: my-secret-pw
      MONGO_INITDB_DATABASE: blog-api
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/db

  test-db:
    image: blog-api
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test-secret-pw
    volumes:
      - test_db_data:/data/db

volumes:
  db_data:
  test_db_data:
